# Generated by Django 3.1.7 on 2021-04-01 13:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210401_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
