# Generated by Django 3.1.7 on 2021-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210401_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follower',
            new_name='Following',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tweet',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='comments', to='network.Comment'),
        ),
    ]
